package eu.kanade.tachiyomi.extension.id.hentaicrot

import eu.kanade.tachiyomi.multisrc.oceanwp.OceanWP

class HentaiCrot : OceanWP("Hentai Crot", "https://hentaicrot.com", "id") {
    override fun getCategoryList() = listOf(
        Pair("Default", ""),
        Pair("3D", "https://hentaicrot.com/category/3d/"),
        Pair("Anal", "https://hentaicrot.com/category/anal/"),
        Pair("Berwarna", "https://hentaicrot.com/category/berwarna/"),
        Pair("Blowjob", "https://hentaicrot.com/category/blowjob/"),
        Pair("Doggy Style", "https://hentaicrot.com/category/doggy-style/"),
        Pair("Double Penetration", "https://hentaicrot.com/category/double-penetration/"),
        Pair("Entot Mama", "https://hentaicrot.com/category/entot-mama/"),
        Pair("Full Color", "https://hentaicrot.com/category/full-color/"),
        Pair("Milftoon", "https://hentaicrot.com/category/milftoon/"),
        Pair("Pelajar", "https://hentaicrot.com/category/pelajar/"),
        Pair("Perkosa", "https://hentaicrot.com/category/perkosa/"),
        Pair("Sedarah", "https://hentaicrot.com/category/sedarah/"),
        Pair("Tante Semok", "https://hentaicrot.com/category/tante-semok/"),
        Pair("Toket Besar", "https://hentaicrot.com/category/toket-besar/"),
        Pair("Uncensored", "https://hentaicrot.com/category/uncensored/"),
    )

    override fun getTagList() = listOf(
        Pair("Default", ""),
        Pair("Ahegao", "https://hentaicrot.com/tag/ahegao/"),
        Pair("Berbikini", "https://hentaicrot.com/tag/berbikini/"),
        Pair("Big Areolae", "https://hentaicrot.com/tag/big-areolae/"),
        Pair("Big Ass", "https://hentaicrot.com/tag/big-ass/"),
        Pair("Big Breasts", "https://hentaicrot.com/tag/big-breasts/"),
        Pair("Big Penis", "https://hentaicrot.com/tag/big-penis/"),
        Pair("Cewek Bohay", "https://hentaicrot.com/tag/cewek-bohay/"),
        Pair("Cewek Montok", "https://hentaicrot.com/tag/cewek-montok/"),
        Pair("Cewek Sange", "https://hentaicrot.com/tag/cewek-sange/"),
        Pair("Cewek Semok", "https://hentaicrot.com/tag/cewek-semok/"),
        Pair("Chubby", "https://hentaicrot.com/tag/chubby/"),
        Pair("Ciuman", "https://hentaicrot.com/tag/ciuman/"),
        Pair("Di Kasur", "https://hentaicrot.com/tag/di-kasur/"),
        Pair("Entot Paksa", "https://hentaicrot.com/tag/entot-paksa/"),
        Pair("Fingering", "https://hentaicrot.com/tag/fingering/"),
        Pair("Gangbang", "https://hentaicrot.com/tag/gangbang/"),
        Pair("Hairy", "https://hentaicrot.com/tag/hairy/"),
        Pair("Hand Job", "https://hentaicrot.com/tag/hand-job/"),
        Pair("Housewife", "https://hentaicrot.com/tag/housewife/"),
        Pair("Ibu Kandung", "https://hentaicrot.com/tag/ibu-kandung/"),
        Pair("Impregnation", "https://hentaicrot.com/tag/impregnation/"),
        Pair("Incest", "https://hentaicrot.com/tag/incest/"),
        Pair("Kacamata", "https://hentaicrot.com/tag/kacamata/"),
        Pair("Lingerie", "https://hentaicrot.com/tag/lingerie/"),
        Pair("Mama Bohay", "https://hentaicrot.com/tag/mama-bohay/"),
        Pair("Mama Montok", "https://hentaicrot.com/tag/mama-montok/"),
        Pair("Mama Semok", "https://hentaicrot.com/tag/mama-semok/"),
        Pair("Masturbation", "https://hentaicrot.com/tag/masturbation/"),
        Pair("MILF", "https://hentaicrot.com/tag/milf/"),
        Pair("Nakadashi", "https://hentaicrot.com/tag/nakadashi/"),
        Pair("Outdoor", "https://hentaicrot.com/tag/outdoor/"),
        Pair("Paizuri", "https://hentaicrot.com/tag/paizuri/"),
        Pair("Ponytail", "https://hentaicrot.com/tag/ponytail/"),
        Pair("Sekolah", "https://hentaicrot.com/tag/sekolah/"),
        Pair("Selingkuh", "https://hentaicrot.com/tag/selingkuh/"),
        Pair("Sex Toys", "https://hentaicrot.com/tag/sex-toys/"),
        Pair("Siswi SMA", "https://hentaicrot.com/tag/siswi-sma/"),
        Pair("Sole Female", "https://hentaicrot.com/tag/sole-female/"),
        Pair("Sole Male", "https://hentaicrot.com/tag/sole-male/"),
        Pair("Stockings", "https://hentaicrot.com/tag/stockings/"),
        Pair("Tante Bohay", "https://hentaicrot.com/tag/tante-bohay/"),
        Pair("Tante Montok", "https://hentaicrot.com/tag/tante-montok/"),
        Pair("Threesome", "https://hentaicrot.com/tag/threesome/"),
        Pair("Vanilla", "https://hentaicrot.com/tag/vanilla/"),
        Pair("X-ray", "https://hentaicrot.com/tag/x-ray/"),
    )
}
