package eu.kanade.tachiyomi.extension.id.holotoon

import eu.kanade.tachiyomi.source.model.Filter

class SortFilter :
    UriPartFilter(
        "Urutkan Berdasarkan",
        arrayOf(
            Pair("Popular", "popular"),
            Pair("Latest", "latest"),
            Pair("A-Z", "alphabet"),
            Pair("Rating", "rating"),
            Pair("New", "new"),
        ),
    )

class TypeFilter :
    UriPartFilter(
        "Tipe",
        arrayOf(
            Pair("Semua", ""),
            Pair("Manga", "manga"),
            Pair("Manhwa", "manhwa"),
            Pair("Manhua", "manhua"),
            Pair("Novel", "novel"),
        ),
    )

class StatusFilter :
    UriPartFilter(
        "Status",
        arrayOf(
            Pair("Semua", ""),
            Pair("Ongoing", "ongoing"),
            Pair("Completed", "completed"),
            Pair("Hiatus", "hiatus"),
            Pair("Canceled", "canceled"),
        ),
    )

class MediaFilter :
    UriPartFilter(
        "Media",
        arrayOf(
            Pair("Semua", ""),
            Pair("Comic", "comic"),
            Pair("Novel", "novel"),
        ),
    )

class GenreFilter : UriPartFilter("Genre", genres)
class TeamFilter : UriPartFilter("Team", teams)

open class UriPartFilter(displayName: String, private val vals: Array<Pair<String, String>>) : Filter.Select<String>(displayName, vals.map { it.first }.toTypedArray()) {
    fun toUriPart() = vals[state].second
}

private val genres = arrayOf(
    "Semua Genre" to "",
    "Action" to "action",
    "Adaptation" to "adaptation",
    "Adult" to "adult",
    "Adventure" to "adventure",
    "Age Gap" to "age-gap",
    "Aliens" to "aliens",
    "Animals" to "animals",
    "Anthology" to "anthology",
    "Bara(ML)" to "baraml",
    "Beasts" to "beasts",
    "Bloody" to "bloody",
    "Bodyswap" to "bodyswap",
    "Boys" to "boys",
    "Cars" to "cars",
    "Cheating/Infidelity" to "cheatinginfidelity",
    "Childhood Friends" to "childhood-friends",
    "College life" to "college-life",
    "Comedy" to "comedy",
    "Contest winning" to "contest-winning",
    "Cooking" to "cooking",
    "Crime" to "crime",
    "Crossdressing" to "crossdressing",
    "Delinquents" to "delinquents",
    "Dementia" to "dementia",
    "Demons" to "demons",
    "Drama" to "drama",
    "Dungeons" to "dungeons",
    "Ecchi" to "ecchi",
    "Emperor's daughter" to "emperors-daughter",
    "Fan-Colored" to "fan-colored",
    "Fantasy" to "fantasy",
    "Fetish" to "fetish",
    "Full Color" to "full-color",
    "Game" to "game",
    "Gender Bender" to "gender-bender",
    "Genderswap" to "genderswap",
    "Ghosts" to "ghosts",
    "Girls" to "girls",
    "Gore" to "gore",
    "Gyaru" to "gyaru",
    "Harem" to "harem",
    "Harlequin" to "harlequin",
    "Hentai" to "hentai",
    "Historical" to "historical",
    "Horror" to "horror",
    "Incest" to "incest",
    "Isekai" to "isekai",
    "Josei(W)" to "joseiw",
    "Kids" to "kids",
    "Kodomo(Kid)" to "kodomokid",
    "Magic" to "magic",
    "Magical Girls" to "magical-girls",
    "Martial Arts" to "martial-arts",
    "Mature" to "mature",
    "Mecha" to "mecha",
    "Medical" to "medical",
    "Military" to "military",
    "Monster Girls" to "monster-girls",
    "Monsters" to "monsters",
    "Music" to "music",
    "Mystery" to "mystery",
    "Netorare/NTR" to "netorarentr",
    "Ninja" to "ninja",
    "Non-human" to "non-human",
    "Office Workers" to "office-workers",
    "Omegaverse" to "omegaverse",
    "Parody" to "parody",
    "Philosophical" to "philosophical",
    "Police" to "police",
    "Post-Apocalyptic" to "post-apocalyptic",
    "Psychological" to "psychological",
    "Regression" to "regression",
    "Reincarnation" to "reincarnation",
    "Revenge" to "revenge",
    "Reverse Harem" to "reverse-harem",
    "Reverse Isekai" to "reverse-isekai",
    "Romance" to "romance",
    "Royal family" to "royal-family",
    "Royalty" to "royalty",
    "Samurai" to "samurai",
    "School Life" to "school-life",
    "Sci-Fi" to "sci-fi",
    "Seinen(M)" to "seinenm",
    "Shoujo ai" to "shoujo-ai",
    "Shoujo(G)" to "shoujog",
    "Shounen ai" to "shounen-ai",
    "Shounen(B)" to "shounenb",
    "Showbiz" to "showbiz",
    "Silver & Golden" to "silver--golden",
    "Slice of Life" to "slice-of-life",
    "SM/BDSM/SUB-DOM" to "smbdsmsub-dom",
    "Smut" to "smut",
    "Space" to "space",
    "Sports" to "sports",
    "Super Power" to "super-power",
    "Superhero" to "superhero",
    "Supernatural" to "supernatural",
    "Survival" to "survival",
    "Thriller" to "thriller",
    "Time Travel" to "time-travel",
    "Tower Climbing" to "tower-climbing",
    "Traditional Games" to "traditional-games",
    "Tragedy" to "tragedy",
    "Transmigration" to "transmigration",
    "Vampires" to "vampires",
    "Video Games" to "video-games",
    "Villainess" to "villainess",
    "Violence" to "violence",
    "Virtual Reality" to "virtual-reality",
    "Wuxia" to "wuxia",
    "Xianxia" to "xianxia",
    "Xuanhuan" to "xuanhuan",
    "Yakuzas" to "yakuzas",
    "Yuri(GL)" to "yurigl",
    "Zombies" to "zombies",
)

private val teams = arrayOf(
    "Semua Translator" to "",
    "aetherveil" to "aetherveil",
    "artemis" to "artemis",
    "ayanatl" to "ayanatl",
    "baby_dragon" to "baby_dragon",
    "capricious" to "capricious",
    "chajan" to "chajan",
    "cherryblossom" to "cherryblossom",
    "creamcake" to "creamcake",
    "faliciakty" to "faliciakty",
    "gummyginger" to "gummyginger",
    "hahaha_" to "hahaha_",
    "holotoon" to "holotoon",
    "hyeenaa" to "hyeenaa",
    "jkminna" to "jkminna",
    "kachangrebus" to "kachangrebus",
    "kanghajun" to "kanghajun",
    "kazuu_" to "kazuu_",
    "kinlith" to "kinlith",
    "kissycat" to "kissycat",
    "kochengoren" to "kochengoren",
    "k_yuna" to "k_yuna",
    "leleon" to "leleon",
    "mawardi_permata" to "mawardi_permata",
    "meissla" to "meissla",
    "miluna" to "miluna",
    "minyoung" to "minyoung",
    "moccacinno" to "moccacinno",
    "mouyiee" to "mouyiee",
    "nheavez" to "nheavez",
    "pinnoy" to "pinnoy",
    "rissevona" to "rissevona",
    "sukatidurzz" to "sukatidurzz",
    "wyrenn" to "wyrenn",
    "zifahx" to "zifahx",
    "zznaty" to "zznaty",
)
