package eu.kanade.tachiyomi.extension.id.comicazen

import eu.kanade.tachiyomi.multisrc.comicaso.Comicaso

class Comicazen :
    Comicaso(
        "Comicazen",
        "https://comicazen.com",
        "id",
    ) {
    override val versionId = 2

    override fun getGenreList(): Array<String> = arrayOf(
        "All",
        "action",
        "Adaptation",
        "adventure",
        "Age Gap",
        "Aliens",
        "Animals",
        "Beasts",
        "Bloody",
        "Bodyswap",
        "boys",
        "Cheating/Infidelity",
        "Childhood Friends",
        "College life",
        "Comedy",
        "Cooking",
        "Crime",
        "Crossdressing",
        "Delinquents",
        "Demons",
        "drama",
        "Dungeons",
        "ecchi",
        "Emperor's daughte",
        "Fantasy",
        "fighting",
        "Full Color",
        "Game",
        "Gender Bender",
        "Genderswap",
        "Ghosts",
        "girl",
        "Girls",
        "gore",
        "Harem",
        "Historical",
        "horror",
        "Incest",
        "Isekai",
        "Josei(W)",
        "Kids",
        "Magic",
        "Magical Girls",
        "manga",
        "Manhua",
        "manhwa",
        "Martial Arts",
        "Mature",
        "Medical",
        "Military",
        "Monster Girls",
        "Monsters",
        "Music",
        "Mystery",
        "NTR",
        "Office Workers",
        "Philosophical",
        "Police",
        "Psychological",
        "Regression",
        "Reincarnation",
        "Revenge",
        "Reverse Harem",
        "Reverse Isekai",
        "Romance",
        "Royal family",
        "Royalty",
        "School Life",
        "Sci-Fi",
        "Seinen(M)",
        "Sejarah",
        "Shoujo(G)",
        "Shounen ai",
        "Shounen(B)",
        "Showbiz",
        "Slice of Life",
        "Smut",
        "Super Power",
        "Superhero",
        "Supernatural",
        "Survival",
        "Thriller",
        "Time Travel",
        "Tower Climbing",
        "Tragedy",
        "Transmigration",
        "Vampires",
        "Video Games",
        "Villainess",
        "Violence",
        "Western",
        "Yuri(GL)",
        "Zombies",
    )
}
