package eu.kanade.tachiyomi.extension.id.pixhentai

import eu.kanade.tachiyomi.multisrc.oceanwp.OceanWP

class PixHentai : OceanWP("Pix Hentai", "https://pixhentai.com", "id") {
    override fun getCategoryList() = listOf(
        Pair("Default", ""),
        Pair("Anal", "https://pixhentai.com/genre/anal/"),
        Pair("Anime", "https://pixhentai.com/genre/anime/"),
        Pair("Athlete", "https://pixhentai.com/genre/athlete/"),
        Pair("Beach", "https://pixhentai.com/genre/beach/"),
        Pair("Bedroom", "https://pixhentai.com/genre/bedroom/"),
        Pair("Big Boobs", "https://pixhentai.com/genre/big-boobs/"),
        Pair("Bikini", "https://pixhentai.com/genre/bikini/"),
        Pair("Blowjob", "https://pixhentai.com/genre/blowjob/"),
        Pair("Bondage", "https://pixhentai.com/genre/bondage/"),
        Pair("Breast Sucking", "https://pixhentai.com/genre/breast-sucking/"),
        Pair("Bukkake", "https://pixhentai.com/genre/bukkake/"),
        Pair("Cheating", "https://pixhentai.com/genre/cheating/"),
        Pair("Classroom", "https://pixhentai.com/genre/classroom/"),
        Pair("Consensual", "https://pixhentai.com/genre/consensual/"),
        Pair("Cosplay", "https://pixhentai.com/genre/cosplay/"),
        Pair("Cowgirl", "https://pixhentai.com/genre/cowgirl/"),
        Pair("Daughter", "https://pixhentai.com/genre/daughter/"),
        Pair("Doctor", "https://pixhentai.com/genre/doctor/"),
        Pair("Doggy", "https://pixhentai.com/genre/doggy/"),
        Pair("Double Penetration", "https://pixhentai.com/genre/double-penetration/"),
        Pair("Drama", "https://pixhentai.com/genre/drama/"),
        Pair("English Translated", "https://pixhentai.com/genre/english-translated/"),
        Pair("Festival", "https://pixhentai.com/genre/festival/"),
        Pair("Fingering", "https://pixhentai.com/genre/fingering/"),
        Pair("Footjob", "https://pixhentai.com/genre/footjob/"),
        Pair("Full Color", "https://pixhentai.com/genre/full-color/"),
        Pair("Girlfriend", "https://pixhentai.com/genre/girlfriend/"),
        Pair("Girls und Panzer", "https://pixhentai.com/genre/girls-und-panzer/"),
        Pair("Glasses", "https://pixhentai.com/genre/glasses/"),
        Pair("Groping", "https://pixhentai.com/genre/groping/"),
        Pair("Gundam Seed Destiny", "https://pixhentai.com/genre/gundam-seed-destiny/"),
        Pair("Handjob", "https://pixhentai.com/genre/handjob/"),
        Pair("Harem", "https://pixhentai.com/genre/harem/"),
        Pair("Hinata", "https://pixhentai.com/genre/hinata/"),
        Pair("Hospital", "https://pixhentai.com/genre/hospital/"),
        Pair("Hot Pants", "https://pixhentai.com/genre/hot-pants/"),
        Pair("Hotel", "https://pixhentai.com/genre/hotel/"),
        Pair("Incest", "https://pixhentai.com/genre/incest/"),
        Pair("Kimono", "https://pixhentai.com/genre/kimono/"),
        Pair("Komik Hentai Indonesia", "https://pixhentai.com/genre/komik-hentai-indonesia/"),
        Pair("Large Breasts", "https://pixhentai.com/genre/large-breasts/"),
        Pair("Lolicon", "https://pixhentai.com/genre/lolicon/"),
        Pair("Macross Frontier", "https://pixhentai.com/genre/macross-frontier/"),
        Pair("Missionary", "https://pixhentai.com/genre/missionary/"),
        Pair("Modern", "https://pixhentai.com/genre/modern/"),
        Pair("Mom", "https://pixhentai.com/genre/mom/"),
        Pair("Mother", "https://pixhentai.com/genre/mother/"),
        Pair("Naruto", "https://pixhentai.com/genre/naruto/"),
        Pair("Nurse", "https://pixhentai.com/genre/nurse/"),
        Pair("Office Lady", "https://pixhentai.com/genre/office-lady/"),
        Pair("Outdoor", "https://pixhentai.com/genre/outdoor/"),
        Pair("Paizuri", "https://pixhentai.com/genre/paizuri/"),
        Pair("Pool", "https://pixhentai.com/genre/pool/"),
        Pair("Rape", "https://pixhentai.com/genre/rape/"),
        Pair("Restaurant", "https://pixhentai.com/genre/restaurant/"),
        Pair("Restroom", "https://pixhentai.com/genre/restroom/"),
        Pair("Romance", "https://pixhentai.com/genre/romance/"),
        Pair("Sakura", "https://pixhentai.com/genre/sakura/"),
        Pair("Small Breasts", "https://pixhentai.com/genre/small-breasts/"),
        Pair("Small Tits", "https://pixhentai.com/genre/small-tits/"),
        Pair("Step Mom", "https://pixhentai.com/genre/step-mom/"),
        Pair("Step Mother", "https://pixhentai.com/genre/step-mother/"),
        Pair("Step Sister", "https://pixhentai.com/genre/step-sister/"),
        Pair("Stockings", "https://pixhentai.com/genre/stockings/"),
        Pair("Student", "https://pixhentai.com/genre/student/"),
        Pair("Swimsuit", "https://pixhentai.com/genre/swimsuit/"),
        Pair("Teacher", "https://pixhentai.com/genre/teacher/"),
        Pair("Teenager", "https://pixhentai.com/genre/teenager/"),
        Pair("Threesome", "https://pixhentai.com/genre/threesome/"),
        Pair("Uncensored", "https://pixhentai.com/genre/uncensored/"),
        Pair("Uncle", "https://pixhentai.com/genre/uncle/"),
        Pair("Uniform", "https://pixhentai.com/genre/uniform/"),
        Pair("Vanilla", "https://pixhentai.com/genre/vanilla/"),
        Pair("Workmate", "https://pixhentai.com/genre/workmate/"),
    )
}
