package eu.kanade.tachiyomi.extension.id.medusascans

import eu.kanade.tachiyomi.multisrc.comicaso.Comicaso

class Medusascans :
    Comicaso(
        "Medusascans",
        "https://medusascans.com",
        "id",
    ) {
    override val versionId = 2

    override fun getGenreList(): Array<String> = arrayOf(
        "All",
        "action",
        "Adaptation",
        "Adult",
        "adventure",
        "Age Gap",
        "Aliens",
        "Animals",
        "Anthology",
        "BDSM",
        "Beasts",
        "Bloody",
        "Bodyswap",
        "boys",
        "Cheating/Infidelity",
        "Childhood Friends",
        "College life",
        "Comedy",
        "Contest winning",
        "Cooking",
        "Crime",
        "Delinquents",
        "Demons",
        "drama",
        "Dungeons",
        "ecchi",
        "Emperor's Daughter",
        "Fantasy",
        "Fetish",
        "Full Color",
        "Game",
        "Gender Bender",
        "Genderswap",
        "Ghosts",
        "girl",
        "gore",
        "Harem",
        "Hentai",
        "Historical",
        "horror",
        "Isekai",
        "Josei(W)",
        "Magic",
        "manga",
        "Manhua",
        "manhwa",
        "Martial Arts",
        "Mature",
        "Medical",
        "Military",
        "Monster Girls",
        "Monsters",
        "Music",
        "Mystery",
        "NTR",
        "Non-human",
        "Office Workers",
        "Omegaverse",
        "Oneshot",
        "Police",
        "Psychological",
        "Regression",
        "Reincarnation",
        "Revenge",
        "Reverse Harem",
        "Romance",
        "Royal family",
        "Royalty",
        "School Life",
        "Sci-Fi",
        "Seinen(M)",
        "Shoujo ai",
        "Shoujo(G)",
        "Shounen ai",
        "Shounen(B)",
        "Showbiz",
        "Slice of Life",
        "SM/BDSM/SUB-DOM",
        "Smut",
        "Space",
        "Sports",
        "Super Power",
        "Supernatural",
        "Survival",
        "Thriller",
        "Time Travel",
        "Tower Climbing",
        "Traditional Games",
        "Tragedy",
        "Transmigration",
        "Vampires",
        "Video Games",
        "Villainess",
        "Violence",
        "Virtual Reality",
        "Western",
        "Wuxia",
        "Yakuzas",
        "Yaoi(BL)",
        "Yuri(GL)",
        "Zombies",
    )
}
