package eu.kanade.tachiyomi.multisrc.scanreader

import eu.kanade.tachiyomi.source.model.Filter

class GenreFilter(name: String, val genres: Array<Pair<String, String>>) : Filter.Select<String>(name, genres.map { it.first }.toTypedArray())

class StatusFilter(name: String, val statuses: Array<Pair<String, String>>) : Filter.Select<String>(name, statuses.map { it.first }.toTypedArray())

class SortFilter(name: String, val sorts: Array<Pair<String, String>>) : Filter.Select<String>(name, sorts.map { it.first }.toTypedArray())

fun getGenreList() = arrayOf(
    "Action" to "action",
    "Adaptation" to "adaptation",
    "Adulte" to "adulte",
    "Adventure" to "adventure",
    "Amitié" to "amitie",
    "Amour" to "amour",
    "Art" to "art",
    "Art Martiaux" to "art-martiaux",
    "Arts martiaux" to "arts-martiaux",
    "Aventure" to "aventure",
    "BL" to "bl",
    "Boys' Love" to "boys-love",
    "Combat" to "combat",
    "Comédie" to "comedie",
    "Comedy" to "comedy",
    "Dark Fantasy" to "dark-fantasy",
    "Délinquants" to "delinquants",
    "Démon" to "demon",
    "Drama" to "drama",
    "Drame" to "drame",
    "Ecchi" to "ecchi",
    "École" to "ecole",
    "Erotique" to "erotique",
    "Famille" to "famille",
    "Fantaisie" to "fantaisie",
    "Fantastique" to "fantastique",
    "Fantasy" to "fantasy",
    "Full Color" to "full-color",
    "Girls' Love" to "girls-love",
    "Gore" to "gore",
    "Guerre" to "guerre",
    "Harem" to "harem",
    "Historical" to "historical",
    "Historique" to "historique",
    "Horreur" to "horreur",
    "Horror" to "horror",
    "Isekai" to "isekai",
    "Jeu" to "jeu",
    "Jeux vidéo" to "jeux-video",
    "Josei" to "josei",
    "Long Strip" to "long-strip",
    "Magie" to "magie",
    "Manga" to "manga",
    "Manhua" to "manhua",
    "Manhwa" to "manhwa",
    "Mature" to "mature",
    "Mecha" to "mecha",
    "Militaire" to "militaire",
    "Moderne" to "moderne",
    "Monstres" to "monstres",
    "Murim" to "murim",
    "Musique" to "musique",
    "Mystère" to "mystere",
    "Mystery" to "mystery",
    "Office Workers" to "office-workers",
    "Policier" to "policier",
    "Post-Apo" to "post-apo",
    "Post-apocalyptique" to "post-apocalyptique",
    "Prison" to "prison",
    "Psychologique" to "psychologique",
    "Régression" to "regression",
    "Réincarnation" to "reincarnation",
    "Returner" to "returner",
    "Romance" to "romance",
    "School life" to "school-life",
    "Sci-fi" to "sci-fi",
    "Science-Fiction" to "science-fiction",
    "Seinen" to "seinen",
    "Shojo" to "shojo",
    "Shonen" to "shonen",
    "Shonen-Ai" to "shonen-ai",
    "Slice of Life" to "slice-of-life",
    "Sport" to "sport",
    "Supernatural" to "supernatural",
    "Supernaturel" to "supernaturel",
    "Surnaturel" to "surnaturel",
    "Survie" to "survie",
    "Thriller" to "thriller",
    "Tragédie" to "tragedie",
    "Tranche de vie" to "tranche-de-vie",
    "Vampires" to "vampires",
    "Vengeance" to "vengeance",
    "Vie scolaire" to "vie-scolaire",
    "Voyage dans le temps" to "voyage-dans-le-temps",
    "Web Comic" to "web-comic",
    "Webcomic" to "webcomic",
    "Yaoi" to "yaoi",
    "Yuri" to "yuri",
)

fun getHentaiGenreList() = arrayOf(
    "Action" to "action",
    "Adaptation" to "adaptation",
    "Adulte" to "adulte",
    "Age Gap" to "age-gap",
    "Amitié" to "amitie",
    "Anthology" to "anthology",
    "Art" to "art",
    "Aventure" to "aventure",
    "BDSM" to "bdsm",
    "Belle-mère" to "belle-mere",
    "Boys' Love" to "boys-love",
    "Campus" to "campus",
    "Comédie" to "comedie",
    "Comedy" to "comedy",
    "Crime" to "crime",
    "Délinquants" to "delinquants",
    "Delinquents" to "delinquents",
    "Domination" to "domination",
    "Doujinshi" to "doujinshi",
    "Drama" to "drama",
    "Drame" to "drame",
    "Ecchi" to "ecchi",
    "Érotique" to "erotique",
    "Famille" to "famille",
    "Fantaisie" to "fantaisie",
    "Fantasy" to "fantasy",
    "Fétichisme" to "fetichisme",
    "Full Color" to "full-color",
    "Genderswap" to "genderswap",
    "Girls' Love" to "girls-love",
    "Gore" to "gore",
    "Hardcore" to "hardcore",
    "Harem" to "harem",
    "Hentai" to "hentai",
    "Historical" to "historical",
    "Historique" to "historique",
    "Horreur" to "horreur",
    "Horror" to "horror",
    "Humiliation" to "humiliation",
    "Inceste" to "inceste",
    "Isekai" to "isekai",
    "Josei" to "josei",
    "Loli" to "loli",
    "Long Strip" to "long-strip",
    "Mafia" to "mafia",
    "Magic" to "magic",
    "Magical Girls" to "magical-girls",
    "Magie" to "magie",
    "Manga" to "manga",
    "Manhua" to "manhua",
    "Manhwa" to "manhwa",
    "Mature" to "mature",
    "MILF" to "milf",
    "Militaire" to "militaire",
    "Monster Girls" to "monster-girls",
    "Monsters" to "monsters",
    "Monstres" to "monstres",
    "Mystère" to "mystere",
    "Mystery" to "mystery",
    "Ninja" to "ninja",
    "Office Workers" to "office-workers",
    "Official Colored" to "official-colored",
    "Omégaverse" to "omegaverse",
    "Oneshot" to "oneshot",
    "Police" to "police",
    "Policier" to "policier",
    "Pornhwa" to "pornhwa",
    "Psychological" to "psychological",
    "Psychologie" to "psychologie",
    "Psychologique" to "psychologique",
    "Réincarnation" to "reincarnation",
    "Reverse Harem" to "reverse-harem",
    "Romance" to "romance",
    "School life" to "school-life",
    "Sci-Fi" to "sci-fi",
    "Seinen" to "seinen",
    "Série courte" to "serie-courte",
    "Sexual Violence" to "sexual-violence",
    "Shojo" to "shojo",
    "Shonen" to "shonen",
    "Slice of life" to "slice-of-life",
    "Smut" to "smut",
    "Softcore" to "softcore",
    "Sport" to "sport",
    "Sports" to "sports",
    "Superhero" to "superhero",
    "Supernatural" to "supernatural",
    "Surnaturel" to "surnaturel",
    "Survie" to "survie",
    "Survival" to "survival",
    "Thriller" to "thriller",
    "Tragédie" to "tragedie",
    "Tranche de vie" to "tranche-de-vie",
    "Trauma" to "trauma",
    "Triangle amoureux" to "triangle-amoureux",
    "Uncensored" to "uncensored",
    "Vengeance" to "vengeance",
    "Video Games" to "video-games",
    "Vie scolaire" to "vie-scolaire",
    "Voyage dans le temps" to "voyage-dans-le-temps",
    "Web Comic" to "web-comic",
    "Webcomic" to "webcomic",
    "Yaoi" to "yaoi",
    "Yuri" to "yuri",
)

fun getStatusList() = arrayOf(
    "Tous les statuts" to "",
    "En cours" to "En cours",
    "Terminé" to "Terminé",
    "Hiatus" to "Hiatus",
    "Licencié" to "Licencié",
)

fun getSortList() = arrayOf(
    "Titre A-Z" to "title",
    "Plus récent" to "date",
    "Plus populaire" to "views",
)
